import type { Metadata } from 'next'
import { Kanit } from 'next/font/google'
import './globals.css'

const kanit = Kanit({ subsets: ['latin'], weight: '700'  })

export const metadata: Metadata = {
  title: 'Guilherme Augusto | Full-Stack Developer',
  description: 'Generated by Guilherme Augusto | Full-Stack Developer',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kanit.className}>{children}</body>
    </html>
  )
}
